spring:
    application:
        name: bnk2WAVE

    jpa:
      hibernate:
        ddl-auto: update # 테이블 구조 자동 생성/수정 (개발 단계용)
      show-sql: true     # 실행되는 SQL을 콘솔에 출력
      properties:
        hibernate:
          format_sql: true # SQL을 보기 좋게 정렬
          dialect: org.hibernate.dialect.OracleDialect # Oracle 사용 시 설정

    config:
      import: "optional:file:.env[.properties]"

    datasource:
      url: ${DB_URL}
      username: ${DB_ID}  # DB 계정명
      password: ${DB_PASSWORD}  # DB 비밀번호
      driver-class-name: oracle.jdbc.OracleDriver

    jwt:
      secret: bnk-wave-secret-key-1234